curl -f so invalid URLs don't create invalid files
lefou/millw pull request #26
Opened 2021-12-16 23:41 UTC by nafg

See https://stackoverflow.com/a/13201595/333643. I've tested this behavior.

Necessary because right now returns a 404 and it's creating `~/.cache/mill/download/0.9.11` as a text file with the string `Not Found`

2021-12-17 07:00 UTC, lefou requested changes
Nice fix, thank you!

2021-12-20 05:13 UTC, nafg commented on millw
> -  CURL_CMD=curl
Then what's the point of it being a variable?

2021-12-21 08:57 UTC, lefou commented on millw
> -  CURL_CMD=curl
It allows to provide an alternative curl implementation, e.g. one, that is not it the `$PATH` or not the first one. It also allows some dry-run for dummies ;-) like this:

```
CURL_CMD="echo curl" millw
```

2021-12-22 09:05 UTC, lefou commented
Superseded by #28

2021-12-22 09:05 UTC, closed without merging