feat: GitHub release CDN support.
lefou/millw pull request #45
Opened 2023-01-13 13:41 UTC by yankun1992

In some areas, the network environment makes downloading files from GitHub release very time-consuming. Fortunately,
some CDN services can speed up GitHub release files. You can use the `GITHUB_RELEASE_CDN` environment variable to add
a CDN url prefix before the original GitHub release file url to speed up your file downloads!

2023-01-14 10:13 UTC, lefou commented
Thank you for this contribution. Is there any documentation about this? Can you provide a link?

2023-01-15 15:19 UTC, yankun1992 commented
There is no official CDN service for the Github release, but there are some third-party CDN acceleration services (aka [jsproxy](https://github.com/EtherDream/jsproxy/)) which based on [Cloudflare Workers](https://workers.cloudflare.com/). For users they can decide for themselves which third-party services to choose.

2023-01-16 15:58 UTC, lefou approved these changes
Looks good. Thank you!

2023-01-16 16:01 UTC, lefou requested changes

2023-01-16 16:01 UTC, lefou commented on millw
> +    ${CURL_CMD} -f -L -o "${DOWNLOAD_FILE}" ${DOWNLOAD_URL}
```suggestion
    ${CURL_CMD} -f -L -o "${DOWNLOAD_FILE}" "${DOWNLOAD_URL}"
```

2023-01-16 16:03 UTC, lefou approved these changes

2023-01-16 16:03 UTC, merged